### ISSUE TITLE
Issues to be implemented as v1.0

### ISSUE THREAD

**Issue by akabekobeko** [vivliostyle/vfm#49]
Consider issues to be implemented as v1.0.

## Must

- [x] #59 chore: Add VFM options to buildProcessorTestingCode
- [x] #56 Command line option "-r" in help should be "-p"
- [x] #50 Change automatic line breaks to optional
- [x] #48 Generated HTML should be human readable
- [x] #47 Invalid HTML `<p><figure>…</figure></p>` is generated
- [x] #67 Remove Fenced block and WAI-ARIA role from v1.0
- [x] #41 Fenced block `::: foos` の末尾の s が消えて `class="foo"` になる
- [x] #34 Language default should be undefined, not 'en'

## Discuss

- #38 svgタグ内の改行がbrタグに変換される

## Deffered

Must、Discuss として検討していたが次期バージョンへ見送りとしたもの

- [ ] #46 Attributes on headings not parsed properly when the heading ends with an inline element

**Comment by akabekobeko** [comment]
v2.0 の remark-parse v9 対応を踏まえ、とりあえず現状設計の範囲で対応できそうなものを Must にしました。そのため構文系は候補になっていませんが「これだけはほしい」などがありましたら本 Issue にコメントをお願いします。

**Comment by akabekobeko** [comment]
対応、もしくは既に済んでいるものは冒頭コメントのリストにチェックマークをつけてゆきます。

**Comment by akabekobeko** [comment]
#34 へ対応したのでチェックをつけた。次回のリリースで反映予定。

**Comment by MurakamiShinyu** [comment]
以下の課題と仕様見直し案について、v1.0ですべて対応は難しいと思いますが、v1.0リリースのあとでは仕様の変更が難しくなるので、仕様見直しを確定すること、廃止・変更予定とする動作を明確化することは必要だと思います。

> VFMの仕様と現状の動作をチェックして各spec issueのコメントに課題と仕様見直し案をまとめた:

- [spec: Auto generate HTML section elements #8](https://github.com/vivliostyle/vfm/issues/8)
  - [コメント: 現状の vfm と Pandoc --section-divs の動作の比較評価](https://github.com/vivliostyle/vfm/issues/8#issuecomment-760207841)
- [spec: Attributes on headings and other elements #9](https://github.com/vivliostyle/vfm/issues/9)
  - [コメント: 現状の vfm での実装状況と課題](https://github.com/vivliostyle/vfm/issues/9#issuecomment-760304439)
- [spec: figure for image container #15](https://github.com/vivliostyle/vfm/issues/15)
  - [コメント: 現状の課題まとめ](https://github.com/vivliostyle/vfm/issues/15#issuecomment-760331260)
- [spec: Fenced blocks #5](https://github.com/vivliostyle/vfm/issues/5)
  - [コメント: 現状の vfm の Fenced blocks 実装とその課題、Pandoc との比較 / HTML 要素名を明示的に指定可能にする拡張案](https://github.com/vivliostyle/vfm/issues/5#issuecomment-768119623)
- [spec: WAI-ARIA role syntax #28](https://github.com/vivliostyle/vfm/issues/28)
  - [コメント: WAI-ARIA role syntax の見直し案](https://github.com/vivliostyle/vfm/issues/28#issuecomment-768171789)

**Comment by MurakamiShinyu** [comment]
**Must** への追加案:
- [Remove Fenced block and WAI-ARIA role from v1.0 (#67)](https://github.com/vivliostyle/vfm/issues/67)

**Comment by akabekobeko** [comment]
#47 と #48 へ対応して 1.0.0-alpha.17 をリリースした。

**Comment by akabekobeko** [comment]
2021/3/7 の開発者会議で @MurakamiShinyu さんから  Frontmatter が機能としていないという報告があった。本 issue として Must にしたものは VFM 開発に慣れる意味もあって修正容易なものを選んで一区切り、と考えていたが Frontmatter も含め全 issue を確認して対応と見送りの判断をしたほうがよいのでそうする。

**Comment by akabekobeko** [comment]
v2.0 見送りのものは Milestone にそれを設定する。よって本 issue 冒頭に挙げるものだけを対応候補としてゆく予定。本 issue で一度 Must/Discuss に挙げながら見送りにしたものだけは Deffered に移動する。

**Comment by akabekobeko** [comment]
v1.0.0 も Milestone として追加。これまで Project v1 を付けていたが Project は Issue をカンバン的にまとめるもので issue 一覧画面には表示されず状況把握し辛いため v1.0 or v2.0 見送り判別は Milestone でゆくことにする。

現時点で登録されている機能とバグ issue について

- v1.0.0 対応したほうがよさそうなものは v1.0.0 指定
- 見送り確定は v2.0.0 指定
- 議論の必要なものは issue 登録者と議論の参加者に対して意見要望コメントを追加

とした。以降は個別の issue で議論するため本件は close する。

**Comment by akabekobeko** [comment]
補足。見送りかを議論中のものでも何らかの Milestone には属しているほうがよいので、とりあえず v1.0.0 を指定しておいた。v1.0.0 時点で登録されたことの明示になる。見送りになったら改めて変更予定。
